"""
Long-form paragraph pools for Equilima Learn tool hubs (≥1500 words per article).
Placeholders: {t0}, {t1}, {t2}, {cluster}, {week}
"""

CLUSTER_OPENERS: dict[str, str] = {
    "Equilima — Research": """<p class="eq-p"><span class="eq-zacks-label">Research desk lens</span>—Equilima&rsquo;s <strong>Research</strong> area is built for the boring part of alpha: reconciling narrative with numbers. Whether you are comparing {t0} to {t1} or stress-testing a story on {t2}, the workflow is the same—read primary sources, write down what would falsify you, then pull live metrics. This guide is intentionally repetitive because discipline is repetitive; flashy calls age poorly, while checklists compound.</p>""",
    "Equilima — Crypto": """<p class="eq-p"><span class="eq-zacks-label">Crypto reality check</span>—Digital assets are volatile, fragmented across venues, and entangled with leverage. Tokens like {t0} and {t1} can move with macro risk one week and decouple the next. Equilima&rsquo;s <strong>Crypto</strong> views are for <em>education and context</em>, not leverage tutorials. If you cannot explain custody, you are not ready to size exposure—regardless of what influencers promised in {week}.</p>""",
    "Equilima — Screener": """<p class="eq-p"><span class="eq-zacks-label">Screener discipline</span>—Good screens are opinionated: they encode liquidity, quality, and risk limits before you fall in love with a story on {t0}. Equilima&rsquo;s <strong>Screener</strong> exists so you can reproduce the same funnel weekly—otherwise you are just shopping tickers. Names such as {t1} and {t2} appear here as <strong>teaching examples only</strong>, not ranked picks.</p>""",
    "Equilima — Backtest": """<p class="eq-p"><span class="eq-zacks-label">Backtest hygiene</span>—Hypothetical performance is where hope goes to get a spreadsheet. When you test rules on {t0} or {t1}, you are learning process, not unlocking prophecy. Equilima&rsquo;s <strong>Backtest</strong> tools should be paired with walk-forward thinking, honest costs, and humility about regimes—especially when social feeds in {week} celebrate curves that forgot friction.</p>""",
    "Equilima — Markets": """<p class="eq-p"><span class="eq-zacks-label">Tape literacy</span>—Indices like {t0} summarize dollars, not moods. Breadth, rates, credit, and FX often explain why {t1} diverges from {t2} even when headlines blame a single CEO. Equilima&rsquo;s <strong>Markets</strong> module is for orienting—not for timing brags. Read this section when you want context, not a hot take.</p>""",
}

# Rotating educational paragraphs (~75–110 words each). Filled with .format(t0=, t1=, t2=, cluster=, week=)
GPARAS: list[str] = [
    """<p class="eq-p">The first skill institutional analysts rehearse is <strong>separating the filing from the forum</strong>. When chatter spikes around {t0}, the question is not whether the crowd is excited—it is whether revenue recognition, segment mix, or working capital changed versus your prior model. Retail learners can mirror that discipline by writing a one-sentence thesis before opening a chart. If you cannot state what evidence would prove you wrong, you are gambling with extra steps.</p>""",
    """<p class="eq-p"><strong>Margin stories age in quarters, not minutes.</strong> A beat on {t1} can hide gross-margin pressure if mix shifted toward lower-quality revenue. Cross-check gross profit dollars, not just percentages, and read footnotes on warranty reserves or rebates. In {cluster} education, the win is building habits that survive a bad tape—because every tape eventually goes bad for someone.</p>""",
    """<p class="eq-p">Liquidity is the silent assumption in every screen. A name tied to {t2} might look statistically perfect yet fail in real trading if average dollar volume cannot absorb your exit. Professionals model impact; learners should at least glance at spreads and depth before celebrating a backtest that assumes frictionless fills. This is especially true when volatility clusters around macro prints referenced in {week}.</p>""",
    """<p class="eq-p">Guidance language is a sentiment lever long before price targets move. Compare how management hedges demand for {t0} versus prior quarters: narrower ranges, softer adjectives, or extra caveats often precede revisions—even when the headline EPS still “wins.” Your job is to log those shifts in your own notes so you are not surprised when the stock reacts to the <em>tone</em> as much as the number.</p>""",
    """<p class="eq-p">Cash flow is where accounting optimism goes to confess. If net income at {t1} races ahead of operating cash flow for multiple quarters, ask why—capitalized costs, working capital pulls, or timing can explain it, but you need a specific explanation tied to the filing, not vibes. Equilima can surface updated metrics, but it cannot replace your reading of the cash flow statement bridge.</p>""",
    """<p class="eq-p">Peer tables are dangerous when copied without normalization. Comparing {t0} to {t2} requires aligned fiscal calendars, consistent lease accounting, and awareness of one-offs like restructuring or legal settlements. A cheap multiple can be a trap; an expensive multiple can price a durable moat. The educational point is to <strong>justify the gap</strong> with operating evidence, not memes.</p>""",
    """<p class="eq-p">Risk factors are boilerplate until one paragraph changes. Diff the 10-K year over year; new wording on regulation, concentration, or supply chain often matters more than a slick deck slide. If you are studying {cluster} themes, keep a “watch list” of risks management admits—and revisit after earnings to see whether actions matched words.</p>""",
    """<p class="eq-p">Scenario thinking beats point forecasts. Instead of asking “where will {t1} trade,” ask what happens to your checklist if growth slows two points, if WACC rises fifty basis points, or if the strongest customer segment stalls. You are not building certainty—you are building <em>robustness</em> so you do not panic on the first red day.</p>""",
    """<p class="eq-p">Options positioning can distort spot prices short term without changing the business. When {t0} squeezes on gamma flows, fundamentals readers should note the dislocation but avoid rewriting a five-year thesis around a weekly chain. Use {cluster} tools for context; use filings for conviction—otherwise you are narrating volatility, not analyzing it.</p>""",
    """<p class="eq-p">International revenue adds FX noise that screens ignore. If {t2} earns a large share overseas, a strong dollar can compress translated sales even when local demand is fine. Read segment geography tables and hedging disclosures before attributing every move to “execution.” This is classic multinational literacy that separates tourists from students.</p>""",
    """<p class="eq-p">Debt covenants and maturity walls matter when credit tightens. Even quality franchises tied to {t1} can face higher refinancing costs that eat buyback capacity or R&amp;D flexibility. A learner-level exercise: plot maturities from the footnotes and ask what rates would need to do to stress free cash flow. No trade signal—just adult supervision for your own expectations.</p>""",
    """<p class="eq-p">Capital returns are not automatically shareholder-friendly. Buybacks at peak multiples or debt-funded repurchases can flatter EPS while raising fragility. When evaluating {t0}, pair repurchase dollars with dilution from stock comp and with leverage trends. The educational payoff is recognizing when “returning cash” is really “re-timing optics.”</p>""",
    """<p class="eq-p">Earnings quality screens often start with accruals: do accounting earnings exceed cash earnings persistently? For {t2}, tie accrual spikes to specific line items—revenue pull-forwards, inventory builds, or reserve releases. If you cannot map it, you do not understand it yet. Repeat the exercise each quarter until the bridge becomes boring; boring is good.</p>""",
    """<p class="eq-p">Sell-side summaries are convenient and sometimes wrong on adjustments. When a headline metric on {t1} disagrees with the 10-Q, trust the filing. Non-GAAP add-backs deserve a skeptical highlight pass—especially stock comp, restructuring, and “adjusted” EBITDA lines that grow faster than GAAP operating income.</p>""",
    """<p class="eq-p">Sector narratives rotate faster than fundamentals. In {week}, you may hear sweeping claims about every name in a theme. Your defense is a short list of <strong>stock-specific</strong> variables for {t0}: what two inputs actually drive the model? If you cannot name them, defer the debate until you can. This is how you avoid becoming a theme tourist.</p>""",
    """<p class="eq-p">Correlation is not identity. {t1} may trade alongside macro beta for stretches, then revert to idiosyncratic drivers. Educational framing: track rolling correlation versus the index, but do not confuse statistical convenience with economic equivalence. Stories age; relationships break—especially around regime shifts.</p>""",
    """<p class="eq-p">Tax rates swing with geography, credits, and one-time items. When comparing {t2} to peers, normalize effective tax trends and read the rate reconciliation table. A “low tax beat” can be accounting timing, not operational excellence. This is the type of detail screens skip but filings provide.</p>""",
    """<p class="eq-p">Customer concentration is a quiet risk multiplier. If {t0} discloses a top customer slice that grew, ask what happens if that relationship pauses—even briefly. Diversification in revenue lines does not always mean diversification in power dynamics. Read the contracts and risk language, not just the pie chart in a blog post.</p>""",
    """<p class="eq-p">Inventory days rising can signal demand weakness—or strategic stocking, or supply-chain buffering. Context matters: compare {t1} to its own history and to honest peers. Tie changes to management commentary on lead times and component availability. The goal is to practice causal thinking, not to jump to a bullish or bearish label.</p>""",
    """<p class="eq-p">R&amp;D capitalization policies change comparability. Some firms expense aggressively; others capitalize software costs where permitted. When studying {t2}, align accounting policies before comparing margins, or you are ranking paint colors under different lighting. Filings spell this out—if you skim, you skew.</p>""",
    """<p class="eq-p">Restructuring charges create “kitchen sink” quarters. A big write-down at {t0} can reset expectations and make the next year look optically clean. Mark the reset date in your notes and track core margins excluding one-offs carefully—without using “adjusted” as a magic erase button for everything inconvenient.</p>""",
    """<p class="eq-p">Dividend durability is cash-flow math dressed up as storytelling. For income learners, pair payout with free cash flow coverage and net leverage—not just yield. {t1} might screen “safe” until cyclicality or patent cliffs intrude. Yields can rise for the wrong reasons; education is learning to tell the difference.</p>""",
    """<p class="eq-p">Event risk clusters around known calendars—earnings, FDA-like milestones, regulatory decisions—yet surprises still arrive from left field. Build a personal “calendar + tail risks” note for {t2}: what is priced, what is possible, and what is unknowable? Humility about the third bucket keeps position sizes sane.</p>""",
    """<p class="eq-p">Analyst revisions are a sentiment thermometer, not a guarantee. When estimates for {t0} drift, ask whether the change reflects new data or herd reshuffling after price moved. Primary-source readers can sometimes spot when the revision cycle is running ahead of fundamentals—or lagging badly after a filing inflection.</p>""",
    """<p class="eq-p">Capital intensity cycles punish rushed screens. If {t1} is entering a heavy capex window, near-term free cash flow may understate long-run value—or mask a bad project. Read management’s return thresholds for projects and compare rhetoric to actual returns on invested capital over time.</p>""",
    """<p class="eq-p">Goodhart’s law applies to screens: when a metric becomes a target, it stops being a good measure. If everyone optimizes the same factor on {t2}, crowding can unwind painfully. Rotate your lens: liquidity first, then quality, then valuation—or another order you can defend. Reproducibility beats novelty.</p>""",
    """<p class="eq-p">Walk-forward humility means accepting that parameters stable in one decade rot in another. Testing on {t0} through a single bull window flatters trend rules; adding a stress decade reveals fragility. Educational backtests prioritize <em>robustness checks</em>, not screenshots for social feeds—especially in {week} when hype runs hot.</p>""",
    """<p class="eq-p">Slippage and fees turn tiny edges into hobbies. If your hypothetical edge on {t1} is a few basis points, model worse fills and wider spreads during stress weeks. Institutions care about implementation shortfall for a reason; retail learners should at least stress-test assumptions instead of trusting defaults.</p>""",
    """<p class="eq-p">Breadth divergences warn that an index move is narrow. When leaders lift the tape while most names stall, the rally can be fragile—though it can also persist longer than cynics expect. Use breadth as context, not prophecy. Pair it with leadership health in names like {t2} you actually follow.</p>""",
    """<p class="eq-p">Rates and duration explain why growth multiples compress when yields rise—mechanically, not morally. Long-dated cash flows discount harder. If you hold {t0} for its terminal value story, rehearse sensitivity tables when the curve moves, even if you are not building a full DCF yet.</p>""",
    """<p class="eq-p">Credit spreads telegraph stress before equities finish arguing. Watch high-yield and investment-grade trends when {cluster} volatility spikes; they often frame whether “risk-on” is shallow positioning or broad appetite. You are learning macro plumbing, not timing every pivot.</p>""",
    """<p class="eq-p">Crypto venues differ in rules, insurance, and failure modes. Treat {t1} as a distinct risk object from the equity that tracks it. Education includes studying custody, withdrawal risk, and the difference between spot and synthetic exposure—before size, not after a headline gap.</p>""",
    """<p class="eq-p">Stablecoins are not risk-free cash—they are issuer and operational risk wrapped in convenience. If you park funds while researching {t2}, read reserve disclosures and counterparty paths. A stable peg can wobble under stress; plan for that mentally even if you never trade it.</p>""",
    """<p class="eq-p">Regulatory headlines reward triage: proposed rule vs enforcement vs politician quote. Only the first two categories sometimes persist. When {t0} whipsaws on news, wait for primary sources before rewriting your notes—emotional trading is expensive homework.</p>""",
    """<p class="eq-p">Position sizing is where knowledge meets adulthood. No article—especially in {cluster}—can know your cash needs, job risk, or debt obligations. Cap downside in dollars you can lose without changing your life. If that cap implies a tiny position, that is data, not failure.</p>""",
    """<p class="eq-p">Journaling beats memory. After you read about {t1}, write three bullets: thesis, falsifiers, unknowns. Revisit monthly. The gap between your old notes and new filings is where learning compounds—and where you catch your own storytelling before the market does.</p>""",
    """<p class="eq-p">Finally, cross-link ideas: {t2} in isolation is a puzzle piece. Connect it to the macro variable you named, the screen rule you tested, and the risk factor you highlighted. Integrated learners survive messy tapes better than ticker collectors—and Equilima is built for that integration, not for anonymous hype.</p>""",
]

# Per-slug ledes (~95–140 words) — Zacks-style punchy openers
ARTICLE_HOOKS: dict[str, str] = {
    "research-fundamentals-walkthrough-aapl-msft-googl": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> If you want the same foundation sell-side juniors drill before they are allowed near a model, start with filings—not feeds. This long guide walks {t0}, {t1}, and {t2} as <em>teaching tickers</em> for segment economics, cash conversion, and risk language. We are not nudging you toward a buy or sell; we are building reading muscles that survive a red week. Expect repetition, checklists, and uncomfortable questions. That is the point.</p>""",
    "research-earnings-quality-nvda-amd-intc-semis": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> Semiconductors are where storytelling meets physics, capacity, and customer concentration. {t0}, {t1}, and {t2} make useful classrooms because the industry cycles hard and the accounting has teeth. We will stress gross-margin paths, inventory tells, and cash versus net income—again, education only. If you finish this guide with three quality checks you can apply next quarter, it did its job.</p>""",
    "research-bank-peer-jpm-bac-gs-fundamentals": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> Banks are spreadsheets wrapped in politics, rates, and credit. Comparing {t0}, {t1}, and {t2} without normalizing business mix is how amateurs sound confident and wrong. This article is a peer-work primer: NII sensitivity, credit costs, markets vs consumer mix, and capital. No “best bank” crown—just a disciplined lens you can reuse every quarter.</p>""",
    "research-dcf-sanity-msft-amzn-meta-education": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> DCF models are assumption machines disguised as precision. Using {t0}, {t1}, and {t2}, we torture terminal growth and discount rates the way skeptical partners do—because tiny changes swing “fair value” wildly. You will not leave with a price target from Equilima; you will leave with sensitivity intuition and a healthy distrust of single-number outputs on social media.</p>""",
    "research-10k-walkthrough-risks-mdna-pg-ko": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> “Boring” staples like {t0} and {t1} are ideal gyms for reading skills—fewer meme shocks, more room to study tone, pricing language, and geographic splits. We focus on risk-factor diffs and MD&amp;A cadence so you can later tackle wilder names without drowning. This is slow food research in a fast-take world.</p>""",
    "crypto-btc-eth-risk-frame-education": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> {t0} and {t1} are not equities with extra volatility—they are different market structures with leverage, custody, and regulatory overlays. This guide builds a risk framework: volatility budgeting, liquidity, and correlation regimes. Nothing here encourages leverage or promises returns. If you want speculation, you still deserve a vocabulary for how you might lose.</p>""",
    "crypto-coin-mstr-equity-proxies-education": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> Stocks like {t0} and {t1} can embed crypto beta <em>plus</em> operating risk, dilution, and accounting choices. The ticker chart is not the same exposure as spot {t2}. We dissect what equity proxies actually price so you stop confusing a rally in coins with a clean read on quarterly fundamentals.</p>""",
    "crypto-alt-liquidity-sol-advanced-risk": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> Altcoins such as {t0} can gap on thin books while narratives sprint ahead of liquidity reality. This article is advanced risk education: slippage, listings, unlock schedules, and correlation spikes in stress. Treat any experimental allocation as tuition you might lose—because many learners do.</p>""",
    "crypto-regulatory-headlines-reading-education": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> Crypto regulation headlines are built to trigger urgency. We teach triage—proposal vs enforcement vs politics—using {t0}, {t1}, and {t2} as context anchors, not legal advice. Slow down, source the primary document, and separate structural change from weekend sentiment.</p>""",
    "crypto-portfolio-sizing-btc-eth-stables-education": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> Sizing is the adult table. Whether you study {t0} or {t1}, define max loss in dollars, assume stables are not magic cash, and reject leverage as a learning tool. Equilima shows charts; it does not know your rent due date—only you do.</p>""",
    "screener-liquidity-first-unh-jpm-xom": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> The best factor in the world fails if you cannot trade it. We start with liquidity and tradability using large, liquid examples like {t0}, {t1}, and {t2}—still not recommendations. Build screens you can actually execute when spreads widen in {week}.</p>""",
    "screener-quality-factors-pg-ko-pep": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> “Quality” is a bundle of metrics, not a vibe. {t0}, {t1}, and {t2} illustrate durability, cash conversion, and the boredom tax when growth is slow. Encode your definition in Equilima’s screener instead of importing someone else’s slogan.</p>""",
    "screener-momentum-nvda-meta-tsla-caveats": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> Momentum screens show what worked—then leave you exposed when positioning unwinds. {t0}, {t1}, and {t2} are case studies in narrative velocity. Pair trend rules with liquidity and drawdown guardrails so you are not the last hero in a crowded trade.</p>""",
    "screener-value-cvs-wba-contrarian": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> Cheap multiples often price real pain. {t0}- and {t1}-style narratives teach debt, coverage, and free cash flow triage so your “value” list is not a trap list. Respect the market’s skepticism until you can explain it better than a meme.</p>""",
    "screener-dividend-schd-style-jnj-pfe": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> Yield hunters step on rakes when they sort highest-first. Compare {t0} and {t1} on payout coverage, cyclicality, and patent cliffs—not just headline yield. Dividend durability screens belong in your funnel before romance.</p>""",
    "backtest-walk-forward-spy-qqq-education": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> One beautiful in-sample curve is a hobby; walk-forward splits are a craft. Using {t0} and {t1}, we explain train/test discipline and why {week} is a dangerous time to trust untested rules promoted online. Hypothetical pasts are not futures.</p>""",
    "backtest-costs-slippage-education": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> Tiny edges die to realistic costs. Stress {t0} versus {t1} universes and you will see how small-cap fiction fills differ from large-cap liquidity. Model friction honestly or keep the backtest as entertainment only.</p>""",
    "backtest-overfitting-degrees-freedom": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> Every indicator knob is a degree of freedom inviting curve-fit. On {t0} and {t1}, simpler rules often survive scrutiny better than twelve-parameter monsters. Delete half your indicators and see what survives—if nothing does, you were fitting noise.</p>""",
    "backtest-regime-change-2020-2022-education": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> 2020 and 2022 taught opposite lessons to the same strategies. Test {t0} and {t1} across regimes or you are optimizing for one weather pattern. Ask which era funded the pretty equity curve you saw on a post.</p>""",
    "backtest-position-sizing-kelly-caution": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> Kelly math is elegant; human estimation error is ugly. Even on a bland benchmark like {t0}, leverage magnifies mistakes. Fractional Kelly is still not personalized advice—just a reminder that survival beats bragging rights.</p>""",
    "markets-breadth-spy-qqq-iwm-education": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> Indices lie by aggregation. {t0}, {t1}, and {t2} help you ask whether rallies are broad or hollow. Breadth is context, not a crystal ball—pair it with leadership health and your own risk plan.</p>""",
    "markets-sector-rotation-xlre-xlk-education": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> Sectors are macro bets in fancy wrappers. {t0}, {t1}, and {t2} encode different sensitivities—rates, credit, energy, growth. Map variables first, trade slogans never. This is framework, not a rotation call.</p>""",
    "markets-vix-vol-regime-education": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> {t1} is not fear—it is implied volatility shaped by hedging demand around {t0}. Learn regimes and event clustering without turning a gauge into a timing idol. Vol products can explode; education warns, not woos.</p>""",
    "markets-rates-curve-tlt-education": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> When {t0} moves, duration math ripples into equities—especially long growth stories. Pair rate shocks with {t1} behavior and stop pretending stocks and bonds live on different planets.</p>""",
    "markets-global-fx-efa-education": """<p class="eq-p eq-zacks-lede"><strong>BLUF:</strong> FX hits multinationals through translation and competitiveness. {t0}, {t1}, and {t2} are handles for learning—not FX trade picks. Read revenue geography in filings, then watch the tape with less confusion.</p>""",
}

ZACKS_SECTION_TITLES: list[str] = [
    "Why this matters on the desk",
    "The playbook—step by step",
    "Where disciplined investors get sloppy",
    "This week: what to watch (education)",
    "Sanity checks before you narrate price",
    "Stress cases that humble simple stories",
    "How Equilima fits into the workflow",
    "Closing the loop—homework that compounds",
]
